- README.md
> README.md update mongodb commands

- Dockerfile-generateconfig
> Fixed installation of yq-package in Dockerfile-generateconfig

- Dockerfile-generateconfig
- Makefile
- docker-generateconfig/processing.sh
> docker-generateconfig fix

- .aws/credentials
- Makefile
- docker-compose.yml
- docker-generateconfig/etc/aws-credentials
- docker-generateconfig/processing.sh
> Fix aws credentials config

- README.md
> README.md added cmd for fix CRLF

- docker-generateconfig/processing.sh
- docker-generateconfig/setListenIp.py
> Fix QUIC listening

- docker-compose.any-sync-admin.yml
- docker-compose.any-sync-consensusnode.yml
- docker-compose.any-sync-coordinator.yml
- docker-compose.any-sync-filenode.yml
- docker-compose.any-sync-node-1.yml
- docker-compose.any-sync-node-all.yml
- docker-compose.yml
> Remove version from docker as it is deprecated

- docker-compose.yml
---
---
The default port type is tcp, so explicitly specify udp in config.
> Fix UDP ports mapping

- docker-compose.yml
> docker-compose.yml fixed redis port

- Dockerfile
- Dockerfile-generateconfig-anyconf
> Dockerfile, Dockerfile-generateconfig-anyconf updated to golang:1.22

- docker-compose.any-sync-consensusnode.yml
- docker-compose.any-sync-coordinator.yml
- docker-compose.any-sync-filenode.yml
- docker-compose.any-sync-node-1.yml
- docker-compose.any-sync-node-all.yml
- docker-compose.yml
---
---
https://docs.docker.com/compose/compose-file/05-services/#image
> `image` may be omitted from a Compose file as long as a `build` section is declared
But on my machine, it will try to pull these images, not to build them:
```
! generateconfig-anyconf Warning pull access denied for generateconfig-anyconf, repository does not exist or may require 'docker login': denied: requested access to the resource is d...
```
```
$ docker compose version 
Docker Compose version 2.27.2
$ docker version 
Client:
Version:           24.0.9
API version:       1.43
Go version:        go1.22.3
Git commit:        v24.0.9
Built:             Thu Jan  1 00:00:00 1970
OS/Arch:           linux/amd64
Context:           default
Server:
Engine:
Version:          24.0.9
API version:      1.43 (minimum version …
```
> Fix pull access warnings for local builds

- docker-generateconfig/setListenIp.py
> docker-generateconfig/setListenIp.py fixed externalListenHost

- Dockerfile-generateconfig-anyconf
- Dockerfile-generateconfig-processing
- docker-compose.yml
https://github.com/anyproto/any-sync-dockercompose/pull/76
---
---
> additional edits for PR76

- docker-compose.yml
> docker-compose.yml remove unused ports

- .env.default
- docker-compose.yml
> 97 image synchronization issues

- Dockerfile-generateconfig-anyconf
> bump go version for any-sync-tools

- docker-compose.yml
> docker-compose.yml added selinux support

- tests/run.d/setExternalListenHost.sh
- tests/run.d/setExternalListenHosts.sh
---
- [x I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)
---
> del symbol / from tests

- docker-compose.yml
> docker-compose.yml added ports config for mongo,redis, minio admin

- Makefile
> Makefile fixed for selinux
